<?php


namespace App\Tests;


use App\Entity\Vendor;
use App\Kernel;
use App\Repository\VendorRepository;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class OrderTest extends KernelTestCase
{
    private VendorRepository $vendorRepository;
    private $entityManager;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::bootKernel([
            'environment' => 'test',
            'debug'       => true,
        ]);

        $kernel = $this->getContainer();

        $this->entityManager = $kernel
            ->get('doctrine')
            ->getManager();
    }

    public function testFirst()
    {
        $vendors = $this->entityManager
            ->getRepository(Vendor::class)
            ->findAll();

        dd($vendors);
    }
}